### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by sryze** [OptimalBits/redbird#143]
I wanted to write a simple reverse proxy script (for local development purposes) but when installing redbird via `npm install -g redbird` it fails with the following error:

```
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\szx\AppData\Roaming\npm\node_modules\redbi
rd\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\szx\AppData\Roaming\npm\node_modules\redbird\node_modules\ursa
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\redbird\node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by keyoti** [comment]
For what it's worth (which may not be a lot) I did it in VS Code on Win 10 without a problem - but I had to manually install all the dependencies with npm first (not sure if that's the only way to do it since I'm new to node)

**Comment by pcnate** [comment]
> For what it's worth (which may not be a lot) I did it in VS Code on Win 10 without a problem - but I had to manually install all the dependencies with npm first (not sure if that's the only way to do it since I'm new to node)

Sames. However I did not install redbird globally. It is installed as a dependency of a project.

Check out my work in progress for local development proxies.
https://github.com/pcnate/red-ampp
