### ISSUE TITLE
Getting 

### ISSUE THREAD

**Issue by joshuaquek** [OptimalBits/redbird#155]
This is my code (following the basic example without registering anything):

```javascript
// index.js
var proxy = require('redbird')({ port: 80});

```

I'm getting this error when I run `node index.js`:

```
{"name":"redbird","hostname":"MyComp","pid":98959,"level":50,"err":{"message":"listen EACCES 0.0.0.0:80","name":"Error","stack":"Error: listen EACCES 0.0.0.0:80\n    at Server.setupListenHandle [as _lis
ten2] (net.js:1313:19)\n    at listenInCluster (net.js:1378:12)\n    at Server.listen (net.js:1466:7)\n    at new ReverseProxy (/Users/mycomp/Desktop/reverse-proxy/node_modules/redbird/lib/proxy.js:122:12)\
n    at ReverseProxy (/Users/mycomp/Desktop/reverse-proxy/node_modules/redbird/lib/proxy.js:24:12)\n    at Object.<anonymous> (/Users/mycomp/Desktop/reverse-proxy/index.js:1:93)\n    at Module._compile
 (internal/modules/cjs/loader.js:678:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)\n    at Module.load (internal/modules/cjs/loader.js:589:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:520:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)\n    at startup (internal/bootstrap/node
.js:228:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)","code":"EACCES"},"msg":"Server Error","time":"2018-06-01T03:09:39.173Z","v":0}
```

**Comment by joshuaquek** [comment]
Any idea why? I cant seem to find an answer anywhere in the issues section. Also, I dont have anything else running on port 80.

**Comment by eliwig** [comment]
This is because you need elevated permissions to bind to anything less than port 1024, not because of redbird. Run the app as sudo or elevate your user level to root. Depending on your setup, check out https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

**Comment by joshuaquek** [comment]
ah.... alright, thanks so much!
