### ISSUE TITLE
npm install redbird error verbose

### ISSUE THREAD

**Issue by joshuaquek** [OptimalBits/redbird#156]
When I try to add it to my project, I get this output, showing that there was an error when running `npm install redbird --save`

Currently I'm using Node 10

```bash
npm install redbird --save                                                      [18/06/20| 2:03PM]
npm WARN deprecated letsencrypt@2.1.9: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN deprecated safetimeout@0.1.2: Please use the 'safe-timers' module instead
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> ursa@0.9.4 install /Users/joshua.quek/Desktop/frontend-api/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/joshua.quek/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joshua.quek/Desktop/frontend-api/node_modules/ursa
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules/ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ redbird@0.7.0
updated 1 package and audited 9808 packages in 16.598s
```

Is anyone else experiencing this error?

**Comment by myrcutio** [comment]
I'm getting the same error on node 8.9.1 (npm 5.5.1)

```
