### ISSUE TITLE
Proxy crashes when using option http2 with transfer.sh

### ISSUE THREAD

**Issue by StiviiK** [OptimalBits/redbird#177]
Using the reverse proxy with [transfer.sh](https://github.com/dutchcoders/transfer.sh/), `http2: true` and letsencrypt certificate, lets the proxy crash
```
"name":"redbird","hostname":"stivik-dev","pid":21800,"level":30,"msg":"Proxying CENSORED/ to 172.17.0.2:80/","time":"2018-10-18T09:17:52.819Z","v":0}
internal/stream_base_commons.js:62
  var err = req.handle.writev(req, chunks, allBuffers);
                       ^

TypeError: req.handle.writev is not a function
    at writevGeneric (internal/stream_base_commons.js:62:24)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
    at doWrite (_stream_writable.js:408:12)
    at clearBuffer (_stream_writable.js:517:5)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at connectionCorkNT (_http_outgoing.js:641:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
When i disable the option `http2` it works fine.
I am not quite sure if this an issue of [transfer.sh](https://github.com/dutchcoders/transfer.sh/), if it so tell me please then i'll report them the issue.

My configuration:
```js
const proxy = redbird({
        port: 80,
        letsencrypt: {
                path: __dirname + '/certs',
                port: 9999
        },
        ssl: {
                http2: true,
                port: 443
        }
});

docker(proxy).register('CENSORED', 'dutchcoders/transfer.sh', {
        ssl: {
                letsencrypt: {
                        email: CENSORED,
                        production: true
                }
        }
});
```

**Comment by morkai** [comment]
Updating spdy to v4.0.0 fixes the issue: https://github.com/spdy-http2/node-spdy/issues/343

**Comment by bhanuc** [comment]
Someone should close issues in this project. So many open issues which have actually been promptly resolved as this one should would send a better picture to new adopters like me.
