### ISSUE TITLE
Error with HTTPS -> HTTP

### ISSUE THREAD

**Issue by longgui0318** [OptimalBits/redbird#178]
Hello,
 i try this proxy. but get error.

this is my code
```js
var Redbird = require('../');
var redbird = Redbird({port: 8081,});
redbird.register("127.0.0.1", "https://www.github.com");
```

errors:
```
Error: Hostname/IP doesn't match certificate's altnames: "IP: 127.0.0.1 is not in the cert's list: "

at Object.checkServerIdentity (tls.js:222:17)
at TLSSocket.<anonymous> (_tls_wrap.js:1109:29)
at emitNone (events.js:106:13)
at TLSSocket.emit (events.js:208:7)
at TLSSocket._finishInit (_tls_wrap.js:637:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```

**Comment by longgui0318** [comment]
fix

```
const proxy = httpProxy.createProxyServer({
  changeOrigin: true// true/false, Default: false - changes the origin of the host header to the target URL
});
```
