### ISSUE TITLE
ECONNRESET crash on websocket upgrade

### ISSUE THREAD

**Issue by morkai** [OptimalBits/redbird#188]
Redbird can crash with
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Thanks to https://github.com/nodejitsu/node-http-proxy/issues/1286#issuecomment-437672954 I was able to narrow it down to `websocketsUpgrade()` not catching the `socket#error` event.
Adding
```js
    socket.on('error', function (err) {
      log && log.error(err, 'WebSocket upgrade error');
    });
```
at the start of `websocketsUpgrade()` fixes the issue, but I'm not familiar enough with Redbird (just started testing) to know if the error can be handled like that right there.

**Comment by manast** [comment]
I think it is fine to handle it like that, so a PR will be greatly appreciated :).
