### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by Gabbersaurus** [OptimalBits/redbird#233]
Had to reinstall my server and while setting up the proxy I got this error:

`TypeError: Cannot read property 'some' of undefined
    at /opt/server/proxy/node_modules/acme-v2/index.js:1219:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
{"name":"redbird","hostname":"arm","pid":5257,"level":50,"err":{"message":"Cannot read property 'some' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'some' of undefined\n    at /opt/server/proxy/node_modules/acme-v2/index.js:1219:30\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"},"msg":"Error registering LetsEncrypt certificates","time":"2019-12-18T15:36:05.256Z","v":0}`

The proxy won't work on HTTPS now sadly. Is there any fix to this?

I'm running it on an ARM based Wandboard

**Comment by manast** [comment]
with that information I am afraid it is not possible to give you any hint...
1) which version of redbird are you using?
2) do you have example code that reproduces the issue?

**Comment by Gabbersaurus** [comment]
Thank you for your quick response.

I tried it on the latest (0.10.0) and on 0.9.1. Both gave the exact same error.
This is the current code that I use:
```
var proxy = require('redbird')({                                                                                                                                        
  port: 80, // http port is needed for LetsEncrypt challenge during request / renewal. Also enables automatic http->https redirection for registered https routes.     
  letsencrypt: {                                                                                                                                                       
    path: __dirname + '/certs',                                                                                                                                        
    port: 9999 // LetsEncrypt minimal web server port for handling challenges. Routed 80->9999, no need to open 9999 in firewall. Default 3000 if not defined.         
  },                                                                                                                                                                   
  ssl: {                                                                                                                                                               
    port: 443, // SSL port used to serve registered https routes with LetsEncrypt certificate.                                                                         
  }                                                                                                                                                                    
});                                                                                                                                                                    
                                                                                                                                                                       
proxy.register('policecoin.pascalbouwhuis.nl', 'http://192.168.178.20:8789', {                                                                                         
  ssl: {                                                                                                                                                               
    letsencrypt: {                                                                                                                                                     
      email: 'p.bouwhuis5+lepolicecoin@gmail.com', // Domain owner/admin email                                                                                         
      production: false, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!                                            
    }                                                                                                                                                                  
  }                                                                                                                                                                    
});    
```

**Comment by Gabbersaurus** [comment]
Thank you for your quick response.

I tried it on the latest (0.10.0) and on 0.9.1. Both gave the exact same error.
This is the current code that I use:
```
var proxy = require('redbird')({                                                                                                                                        
  port: 80, // http port is needed for LetsEncrypt challenge during request / renewal. Also enables automatic http->https redirection for registered https routes.     
  letsencrypt: {                                                                                                                                                       
    path: __dirname + '/certs',                                                                                                                                        
    port: 9999 // LetsEncrypt minimal web server port for handling challenges. Routed 80->9999, no need to open 9999 in firewall. Default 3000 if not defined.         
  },                                                                                                                                                                   
  ssl: {                                                                                                                                                               
    port: 443, // SSL port used to serve registered https routes with LetsEncrypt certificate.                                                                         
  }                                                                                                                                                                    
});                                                                                                                                                                    
                                                                                                                                                                       
proxy.register('x', 'x', {                                                                                         
  ssl: {                                                                                                                                                               
    letsencrypt: {                                                                                                                                                     
      email: 'x', // Domain owner/admin email                                                                                         
      production: false, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!                                            
    }                                                                                                                                                                  
  }                                                                                                                                                                    
});    
```                          
(sorry, deleted my original reply because I forgot to remove my personal info)

**Comment by Gabbersaurus** [comment]
Downgraded to node 9 to test it and I get the same error.

`
{"level":30,"time":1576685909494,"pid":6572,"hostname":"arm","name":"redbird","msg":"LetsEncrypt CA trying to validate challenge /opt/server/proxy/certs/**x**/.well-known/acme-challenge/test-**x**","v":1}
[acme-v2] handled(?) rejection as errback:
TypeError: Cannot read property 'some' of undefined
    at /opt/server/proxy/node_modules/acme-v2/index.js:1219:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
`

**Comment by Gabbersaurus** [comment]
Tried it on another Debian server where it used to work, same error.

**Comment by manast** [comment]
cannot reproduce using your example code (note that I had to change to a valid email address):
```
{"level":30,"time":1576690001171,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Initializing letsencrypt, path /Users/manuelastudillo/Dev/tmp/certs, port: 9999","v":1}
{"level":30,"time":1576690001183,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Listening to HTTPS requests on port 443","v":1}
{"level":30,"time":1576690001184,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Started a Redbird reverse proxy server on port 80","v":1}
{"level":30,"time":1576690001185,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Getting Lets Encrypt certificates for x","v":1}
{"level":30,"time":1576690001221,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","0":false,"1":"created middleware","msg":"Lets encrypt debugger","v":1}
{"level":30,"time":1576690001225,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","from":{"protocol":"http:","slashes":true,"auth":null,"host":"x","port":null,"hostname":"x","hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"http://x/"},"to":{"protocol":"http:","slashes":true,"auth":null,"host":"x","port":null,"hostname":"x","hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"http://x/","sslRedirect":true,"useTargetHostHeader":false},"msg":"Registered a new route","v":1}
{"level":30,"time":1576690001228,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","0":false,"1":"checkAsync failed to find certificates","msg":"Lets encrypt debugger","v":1}
{"level":30,"time":1576690001229,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Manually registering certificate for x","v":1}
{"level":30,"time":1576690001231,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","0":false,"1":"checkAsync failed to find certificates","msg":"Lets encrypt debugger","v":1}
[acme-v2] handled(?) rejection as errback:
Error: account error: 400 {"type":"urn:ietf:params:acme:error:invalidEmail","detail":"Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden","status":400}
{"termsOfServiceAgreed":true,"onlyReturnExisting":false,"contact":["mailto:john@example.com"]}
    at /Users/manuelastudillo/Dev/tmp/node_modules/acme-v2/index.js:240:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
{"level":50,"time":1576690003684,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Error registering LetsEncrypt certificates","stack":"Error: account error: 400 {\"type\":\"urn:ietf:params:acme:error:invalidEmail\",\"detail\":\"Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden\",\"status\":400}\n{\"termsOfServiceAgreed\":true,\"onlyReturnExisting\":false,\"contact\":[\"mailto:john@example.com\"]}\n    at /Users/manuelastudillo/Dev/tmp/node_modules/acme-v2/index.js:240:14\n    at process._tickCallback (internal/process/next_tick.js:68:7)","type":"Error","v":1}
{"level":30,"time":1576690003684,"pid":30374,"hostname":"Manuels-MacBook-Pro-2.local","name":"redbird","msg":"Could not get any certs for x","v":1}


```

**Comment by manast** [comment]
the example above is not complete, I need something I can copy paste locally and reproduce...

**Comment by aschenoni** [comment]
After hitting this same issue for several hours I discovered setting `production: true` fixes the 405 method not allowed that causes this rejection.

**Comment by cmawhorter** [comment]
i'm using greenlock not redbird and i'm seeing this too.  something is wrong in a greenlock dependency but i haven't figured out what yet. i'd recommend pegging the greenlock version in package.json. their releases are.... flakey.

**Comment by boid-com** [comment]
Any updates on this?

**Comment by RezaErfani67** [comment]
after i change {production:true} problem resolved...
any update?

**Comment by ZeusTheMighty** [comment]
Downgrading to Node v11 fixed the issue for me. Below is my implementation in Typescript.

```
import * as Proxy from 'redbird';
const proxy = new Proxy({
  port: '80',
  letsencrypt: {
    path: __dirname + '/certs',
    port: 9999,
  },
  ssl: {
    http2: true,
    port: 443,
  },
});
```
and then calling it like so

```
proxy.register("example.com", "localhost", {
      ssl: {
        letsencrypt: {
          email: 'your@email.com',
          production: true,
        },
      },
    });
```

Hope I was able to help you, stranger from the future!

**Comment by nbriz** [comment]
i'm also having this issue. 

i've tried various different ways to resolve it, including switching between `prouction: true` and `production: false` as @aschenoni mentioned, trying different versions of node (switching between various using nvm) as well as different variatons on the general config code. all that said, it's hard to share exactly what my code looks like (as i've written variations). but...

```js
// generally speaking, it looks like this...
const proxy = require('redbird')({
  port: 80,
  letsencrypt: { path: 'certs', port: 3000 },
  ssl: { port: 443 }
})

// ..with a config that looks like this...
const config = {
  ssl: { letsencrypt: { email: 'my@email.com', production: false } }
}

// ...which i use like this...

proxy.register('firstdomain.com', `http://localhost:${port}`, config)
proxy.register('seconddomain.com', `http://localhost:${port}`, config)
// ...etc...
```

but despite the variations, i keep getting this redibrd error:

> LetsEncrypt CA trying to validate challenge certs/mydomain.com/.well-known/acme-challenge/test-4476763e84d465b0b304b68c5157bb36-0

followed by this:

```
[acme-v2] handled(?) rejection as errback:
TypeError: Cannot read property 'some' of undefined
    at /root/SERVER/node_modules/acme-v2/index.js:1219:30
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

which as @cmawhorter mentions, does seem to be a dependency. i edited the file referenced in the error in order to log the undefined object causing the issue, and when i did i got:
```
{
  type: 'urn:ietf:params:acme:error:malformed',
  detail: 'Method not allowed',
  status: 405
}
```

if it helps, here's the chain of redbird error messages that follow:

- Error registering LetsEncrypt certificates
- Could not get any certs for mydomain.com
- ERR_SSL_NO_SUITABLE_SIGNATURE_ALGORITHM

**Comment by mattwelke** [comment]
Ran into this today while putting together a minimal example from the readme and some GitHub issues. Switching to `production: true` got me past this error too, but resulted in me getting a different error:

```
{"level":30,"time":1609194195775,"pid":40765,"hostname":"redbird-test","name":"redbird","0":false,"1":"setChallenge called for 'REDACTED'","msg":"Lets encrypt debugger","v":1}
[acme-v2] handled(?) rejection as errback:
Error: [acme-v2] (E_STATE_INVALID) challenge state for 'REDACTED': 'invalid'
    at /home/REDACTED/redbird-test/node_modules/acme-v2/index.js:794:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
{"level":50,"time":1609194217524,"pid":40765,"hostname":"redbird-test","name":"redbird","msg":"Error registering LetsEncrypt certificates","stack":"Error: [acme-v2] (E_STATE_INVALID) challenge state for 'REDACTED': 'invalid'\n    at /home/REDACTED/redbird-test/node_modules/acme-v2/index.js:794:27\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","type":"Error","v":1}
{"level":30,"time":1609194217525,"pid":40765,"hostname":"redbird-test","name":"redbird","msg":"Could not get any certs for REDACTED","v":1}
```

My code:

```js
var proxy = require('redbird')({
  port: 80,
  ssl: {
    port: 443,
  },
  letsencrypt: {
    path: '/home/REDACTED/redbird/certs',
  },
});

proxy.register('REDACTED', 'http://localhost:8081', {
  ssl: {
    letsencrypt: {
      email: 'REDACTED', // Domain owner/admin email
      production: true, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!
    }
  }
});
```

**Comment by pcnate** [comment]
for me this seems to happen only when using production: false which I am using for testing and diagnosing other issues....
Seems redbird could use a rewrite....
