### ISSUE TITLE
Proxy stalling indefinitly

### ISSUE THREAD

**Issue by TheKnarf** [OptimalBits/redbird#30]
So I have setup the proxy in a gulpfile:

```JavaScript
var proxy = redbird({port: 8082});
proxy.register('http://localhost:8082', 'http://localhost:8081');
proxy.register('http://localhost:8082/api', 'http://localhost:8080/api');
```

Curl agains the server directly work, but trying to run curl against the redbird proxy won't work.

```
$ curl http://localhost:8080/api
{"endpoints":["bye","hello","resource"]}%
$ curl http://localhost:8082/api
```

The error from the console I'm running `gulp redbird` in:

```json
{
   "name":"redbird",
   "hostname":"Franks-MBP",
   "pid":66293,
   "level":50,
   "err":{
      "message":"connect ECONNREFUSED 127.0.0.1:8080",
      "name":"Error",
      "stack":"Error: connect ECONNREFUSED 127.0.0.1:8080\n    at Object.exports._errnoException (util.js:874:11)\n    at exports._exceptionWithHostPort (util.js:897:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)",
      "code":"ECONNREFUSED"
   },
   "msg":"Proxy Error",
   "time":"2015-12-10T16:50:30.723Z",
   "v":0
}
```

Showing `localhost:8082` in the browser works, but not if I go to `localhost:8082/api`.

**Comment by TheKnarf** [comment]
The problem was that I had started the php server as `php -S localhost:8080` instead of `php -S 127.0.0.1:8080`. Would it be possible in the future to make it so that the proxy still sends the correct hostname to the server its a proxy for?
