### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by yeya** [OptimalBits/redbird#58]
I don't know ecxactly when it happens, but i'm sure it's because 8e72b6bd70ad190e065869eb5257b90f14aa46ce.
So #57 isn't really fixed
```

/redbird/node_modules/redbird/lib/proxy.js:392
  host = host.toLowerCase();
             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at ReverseProxy.resolve (/home/yehuda/redbird/node_modules/redbird/lib/proxy.js:392:14)
    at ReverseProxy._getTarget (/home/yehuda/redbird/node_modules/redbird/lib/proxy.js:442:20)
    at Server.<anonymous> (/home/yehuda/redbird/node_modules/redbird/lib/proxy.js:89:26)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

```

**Comment by manast** [comment]
A defensive fix has been released, but it would be quite interesting to understand why host gets undefined in this particular situation.

**Comment by awb99** [comment]
II just installed redbird 2 days ago; I also get the toLowerCase errror; I assume it is due to a missing
catchall domain?

```
{"name":"redbird","hostname":"backoffice","pid":32368,"level":40,"src":"www.558uu.com","url":"/","msg":"no valid route found for given source","time":"2016-07-19T06:40:15.519Z","v":0}
/root/domainrouter/node_modules/redbird/lib/proxy.js:392
  host = host || host.toLowerCase();
                     ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at ReverseProxy.resolve (/root/domainrouter/node_modules/redbird/lib/proxy.js:392:22)
    at ReverseProxy._getTarget (/root/domainrouter/node_modules/redbird/lib/proxy.js:442:20)
    at Server.<anonymous> (/root/domainrouter/node_modules/redbird/lib/proxy.js:89:26)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

```

**Comment by yeya** [comment]
Update the last commit, I think he didn't change the version so npm didn't
got update
