### ISSUE TITLE
Unable to use redbird on Ubuntu 12.04

### ISSUE THREAD

**Issue by bakulaw** [OptimalBits/redbird#76]
var proxy = require('redbird')({port: 80, xfwd: false});
proxy.register("some.net", "http://1.2.3.4:8080");
proxy.register("some.net/node", "http://1.2.3.4:3000");

node_modules/redbird/lib/proxy.js:401
      function renewCertificate() {
      ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/enutritionista/node_modules/redbird/index.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by manast** [comment]
what version of node are you using? you should use 4+.

**Comment by aek** [comment]
No activity for about a month here, so it seems that the issue can be closed because it's related to node version
